name: Issue assignment

on:
  issues:
    types: [opened]

permissions: read-all

jobs:
  auto-assign:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        # pozil/auto-assign-issue v3.0.0
        uses: pozil/auto-assign-issue@v4.0.1
        with:
          assignees: neverased
          numOfAssignee: 1
