name: Check build

on:
  pull_request:
    branches:
      - main
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Create .env file
        run: echo "SECRET=${{ secrets.ENV }}" > .env

      - name: Create google-credentials.json file
        run: echo "${{ secrets.GOOGLE_API }}" > sos-aio-bot-40e1568bd219.json

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

