name: Deploy

on:
  release:
    types: [published]
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check runner
        run: echo "Runner is running on ${{ runner.os }}"

      - name: Check if NVM is installed
        run: |
          if ! command -v nvm &> /dev/null
          then
                  echo "NVM is not installed"
                  echo "Installing NVM"
                  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
                  source ~/.nvm/nvm.sh
                  echo "NVM installed"
          else
                  echo "NVM is installed"
          fi

      - name: Check if node is installed
        run: |
          if ! command -v node &> /dev/null
          then
                  echo "Node is not installed"
                  echo "Installing node"
                  nvm install node
                  nvm use node
                  echo "Node installed"
          else
                  echo "Node is installed"
          fi

      - name: Kill previous deployments
        run: kill $(lsof -t -i:3500)

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "SECRET=${{ secrets.ENV }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy application
        run: npm run start:prod
