name: Deploy

on:
  release:
    types: [published]
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Kill previous deployments
        run: lsof -t -i:3500 | xargs -r kill

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "SECRET=${{ secrets.ENV }}" > .env

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'
      - run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy application
        run: npm run start:prod
