name: Close as a support issue
on:
  issues:
    types: [labeled]

permissions: read-all

jobs:
  build:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        # peter-evans/close-issue v3.0.2
        uses: peter-evans/close-issue@05dff7ca07116e5707cfb3a3cd4af7bb5e43524c
        if: contains(github.event.issue.labels.*.name, 'support')
        with:
          comment: |
            Sorry, but we'd like to keep issues related to code in this repository. Thank you 🙇

            If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)

            If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)
